services:
  - type: web
    name: sendinchat-server
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install --only-binary :all: -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_ONLY_BINARY
        value: ":all:"
